# Generated by Django 4.1.1 on 2022-12-21 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hospitalfee", unique_together={("product", "hospital")},
        ),
    ]
