# Generated by Django 4.1.1 on 2022-12-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_hospitalfee_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospitalfee", old_name="hospital", new_name="hospital_id",
        ),
        migrations.RenameField(
            model_name="hospitalfee", old_name="product", new_name="product_id",
        ),
        migrations.AlterUniqueTogether(
            name="hospitalfee", unique_together={("product_id", "hospital_id")},
        ),
    ]
