# Generated by Django 4.1.1 on 2022-12-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_clinicfee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clinicfee", old_name="hospital_id", new_name="clinic_id",
        ),
        migrations.AlterUniqueTogether(
            name="clinicfee", unique_together={("product_id", "clinic_id")},
        ),
    ]
