# Generated by Django 4.1.1 on 2022-12-21 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_rename_hospital_id_clinicfee_clinic_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabFee",
            fields=[
                (
                    "fees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "lab_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labfees",
                        to="base.hospital",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labfees",
                        to="base.product",
                    ),
                ),
            ],
            options={"unique_together": {("product_id", "lab_id")},},
        ),
    ]
